[build]
  command = "npm install" # The build command, which installs your dependencies
  functions = "/" # The directory for serverless functions

[[redirects]]
  from = "/*"
  to = "/.netlify/index.mjs"
  status = 200

