[build]
  command = "npm install" # The build command, which installs your dependencies
  functions = "/" # The directory for serverless functions
  publish = "public"
  node_version = "16"

[[redirects]]
  from = "/*"
  to = "/.netlify/index.mjs"
  status = 200

