[build]
  command = "npm install" # The build command, which installs your dependencies
  functions = "functions" # The directory for serverless functions
  publish = "public"
  node_version = "16"



[functions]
node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index.mjs"
  status = 200